[package]
name = "AONT-RS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aont = "0.1.1"
rabin_ida = "0.1.3"
